# Skeletons

_skeleton_main:
    head:
        template: "header/head"
    nav:
        template: "menu/menu"
    body:
        template: "body/main"
    footer:
        template: "footer/footer"

_skeleton_releases:
    head:
        template: "header/head"
    nav:
        template: "menu/menu"
    body:
        template: "body/releases"
    footer:
        template: "footer/footer"

_skeleton_doc:
    head:
        template: "header/head"
    nav:
        template: "menu/menu"
    body:
        template: "body/doc"
    footer:
        template: "footer/footer"
